#!/bin/bash
# Script for uninstall sayahac tools

# ----- sayahac Team -----

# Feel free to share any ideas with the
# project!
#
# -------------------------

clear

echo "

";

if [ "$PREFIX" = "/data/data/com.termux/files/usr" ]; then

    INSTALL_DIR="$PREFIX/usr/share/doc/sayahac"

    BIN_DIR="$PREFIX/bin/"

    BASH_PATH="$PREFIX/bin/bash"

    TERMUX=true

elif [ "$(uname)" = "Darwin" ]; then

    INSTALL_DIR="/usr/local/sayahac"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

else

    INSTALL_DIR="$HOME/.sayahac"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

fi

echo "[✔] Checking directories...";

if [ -d "$INSTALL_DIR" ]; then

        rm -rf "$INSTALL_DIR"

        rm "$BIN_DIR/sayahac*"

        sudo rm -rf "$INSTALL_DIR"

        sudo rm "$BIN_DIR/sayahac*"

    else

        echo "[✘] If you want to uninstall you must remove previous installations [✘] ";

        echo "[✘] Failed! [✘] ";

fi

echo "[✔] Cleaning up old directories...";

if [ -d "$ETC_DIR/Root-012" ]; then

    echo "$DIR_FOUND_TEXT"

    if [ "$TERMUX" = true ]; then

        rm -rf "$ETC_DIR/Root-012"

    else

        sudo rm -rf "$ETC_DIR/Root-012"

    fi

fi

clear

clear

echo "[✔] all good!"
